#PBS -N MPI_AoS
#PBS -o ./Aosbind.txt
#PBS -e ./Aos.e

#PBS -q shortCPUQ
#PBS -l walltime=3:00:00
#PBS -l select=10:ncpus=10:mpiprocs=1:ompthreads=10:mem=100gb

module load OpenMPI/4.1.6-GCC-13.2.0

# Print the name of the file that contains the list of the nodes assigned to the job and list all the nodes
NODES=$(cat $PBS_NODEFILE)
echo The running nodes are $NODES

# Get the list of unique nodes assigned to the job
NODES=$(sort -u $PBS_NODEFILE)
echo The running nodes are $NODES

#Loop through each node and get architecture information
for NODE in $NODES; do
    echo "Node: $NODE"
    ssh $NODE "lscpu"
done

cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=10

echo weak_scaling
mpirun -np 1 --map-by node ./MPI_AoS.o 7
mpirun -np 2 --map-by node ./MPI_AoS.o 7
mpirun -np 4 --map-by node ./MPI_AoS.o 7
mpirun -np 5 --map-by node ./MPI_AoS.o 7
mpirun -np 6 --map-by node ./MPI_AoS.o 7
mpirun -np 7 --map-by node ./MPI_AoS.o 7
mpirun -np 8 --map-by node ./MPI_AoS.o 7
mpirun -np 9 --map-by node ./MPI_AoS.o 7
mpirun -np 10 --map-by node ./MPI_AoS.o 7 
echo strong_scaling
mpirun -np 1 --map-by node ./MPI_AoS.o 7 1000000000
mpirun -np 2 --map-by node ./MPI_AoS.o 7 1000000000
mpirun -np 4 --map-by node ./MPI_AoS.o 7 1000000000
mpirun -np 5 --map-by node ./MPI_AoS.o 7 1000000000
mpirun -np 8 --map-by node ./MPI_AoS.o 7 1000000000
mpirun -np 10 --map-by node ./MPI_AoS.o 7 1000000000
