#PBS -N weak_ompavx
#PBS -o ../PBS/weak_scaling.txt
#PBS -e ../PBS/weak_scaling.e

#PBS -q shortCPUQ
#PBS -l walltime=3:00:00
#PBS -l select=1:ncpus=10:mem=200gb

module load OpenMPI/4.1.4-GCC-12.2.0

# Print the name of the file that contains the list of the nodes assigned to the job and list all the nodes
NODES=$(cat $PBS_NODEFILE)
echo The running nodes are $NODES

# Get the list of unique nodes assigned to the job
NODES=$(sort -u $PBS_NODEFILE)
echo The running nodes are $NODES

#Loop through each node and get architecture information
for NODE in $NODES; do
    echo "Node: $NODE"
    ssh $NODE "lscpu"
done

cd $PBS_O_WORKDIR
cd ../Source/

./shared.o 7 1
./shared.o 7 2
./shared.o 7 3
./shared.o 7 4
./shared.o 7 5
./shared.o 7 6
./shared.o 7 7
./shared.o 7 8
./shared.o 7 9
./shared.o 7 10
